version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: luna
      MONGO_INITDB_ROOT_PASSWORD: crafts
    ports:
      - 27017:27017
    expose:
      - 27017
